### ISSUE TITLE
Clicking on a link in the "OAP Repo Id" column on the "View Submissions" screen logs out the current user

### ISSUE THREAD

**Issue by emetsger** [DataConservancy/pass-ember#102]
1. Navigate to http://34.200.235.123/login with caching _enabled_
2. Click View Submissions (edited)
3. Click on "775054 (NIHMSID)" which _should_ take you to http://34.200.235.123/submissions 

**Instead of getting to the submissions page** I get redirected to the login screen

**Comment by markpatton** [comment]
The issue is the oai repo id uris. It is supposed to open up to some other location. 
But it doesn't use target=_blank and the uris are empty so confusingly its getting linked to an absolute uri to /submissions which will reload the app and confuse matters.

The formatting of that cell is controlled by app/templates/components/submissions-repoid-cell.hbs and the test data can be changed.
